import cv2
import gradio as gr
import numpy as np
import torch
from PIL import Image
from transformers import CLIPImageProcessor, CLIPVisionModel

# Tector's own detector: CLIP ViT-L/14 image features + a logistic-regression head we trained
# (training/ folder) on real photos vs 8 generators (Midjourney, SD, BigGAN, StyleGAN faces, ...).
# Held-out accuracy 91% vs 56% for the best off-the-shelf model we benchmarked.
CLIP_MODEL = "openai/clip-vit-large-patch14"
processor = CLIPImageProcessor.from_pretrained(CLIP_MODEL)
clip = CLIPVisionModel.from_pretrained(CLIP_MODEL).eval()
head = np.load("tector_head.npz")
coef, intercept = head["coef"], float(head["intercept"])

MAX_VIDEO_FRAMES = 20


def ai_probs(images):
    """Probability that each RGB PIL image is AI-generated."""
    with torch.no_grad():
        feats = clip(**processor(images=images, return_tensors="pt")).pooler_output.numpy()
    feats /= np.linalg.norm(feats, axis=1, keepdims=True)
    return 1 / (1 + np.exp(-(feats @ coef + intercept)))


def verdict_html(prob, detail):
    if prob >= 0.7:
        color, text = "#dc2626", "Likely AI-generated"
    elif prob <= 0.3:
        color, text = "#16a34a", "Likely real"
    else:
        color, text = "#d97706", "Uncertain"
    return (
        f'<div style="padding:18px;border-radius:12px;background:{color};color:white;text-align:center">'
        f'<div style="font-size:26px;font-weight:700">{text}</div>'
        f'<div style="font-size:16px;opacity:.9">{prob:.0%} probability of AI generation · {detail}</div>'
        f"</div>"
    )


def build_outputs(prob, detail):
    return verdict_html(prob, detail), {"AI-generated": prob, "Real": 1 - prob}


def analyze_image(img):
    if img is None:
        raise gr.Error("Please upload an image first.")
    return build_outputs(float(ai_probs([img.convert("RGB")])[0]), "single image")


def detect(img):
    """JSON endpoint used by the desktop watcher agent."""
    prob = float(ai_probs([img.convert("RGB")])[0])
    return {"overall": prob, "ai_prob": prob}


def detect_batch(paths):
    """JSON endpoint for the watcher: scores several screen regions in one CLIP batch."""
    if not paths:
        return {"probs": []}
    probs = ai_probs([Image.open(p).convert("RGB") for p in paths])
    return {"probs": [float(p) for p in probs]}


def analyze_video(path):
    if not path:
        raise gr.Error("Please upload a video first.")
    cap = cv2.VideoCapture(path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or 1
    step = max(1, total // MAX_VIDEO_FRAMES)  # spread samples evenly across the clip
    frames = []
    for idx in range(0, total, step):
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ok, frame = cap.read()
        if not ok or len(frames) >= MAX_VIDEO_FRAMES:
            break
        frames.append(Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)))
    cap.release()
    if not frames:
        raise gr.Error("Couldn't read any frames from this video.")
    probs = ai_probs(frames)
    return build_outputs(float(probs.mean()), f"{len(frames)} frames sampled, most suspicious {probs.max():.0%}")


with gr.Blocks(title="Tector") as demo:
    gr.Markdown(
        "# Tector\n"
        "**Spot AI-generated images, videos and deepfakes.** Upload an image or a short video to check "
        "whether it was generated by AI."
    )
    with gr.Tab("Image"):
        with gr.Row():
            with gr.Column():
                img_in = gr.Image(type="pil", label="Image")
                img_btn = gr.Button("Analyze image", variant="primary")
            with gr.Column():
                img_verdict = gr.HTML()
                img_label = gr.Label(label="Tector detector")
        img_btn.click(analyze_image, img_in, [img_verdict, img_label], api_name="analyze_image")
    with gr.Tab("Video"):
        with gr.Row():
            with gr.Column():
                vid_in = gr.Video(label="Video (short clips work best)")
                vid_btn = gr.Button("Analyze video", variant="primary")
            with gr.Column():
                vid_verdict = gr.HTML()
                vid_label = gr.Label(label="Tector detector (avg over frames)")
        vid_btn.click(analyze_video, vid_in, [vid_verdict, vid_label], api_name="analyze_video")
    # Hidden components that expose a plain JSON API at /detect for the desktop agent
    with gr.Row(visible=False):
        api_in = gr.Image(type="pil")
        api_out = gr.JSON()
        api_btn = gr.Button()
    api_btn.click(detect, api_in, api_out, api_name="detect")
    with gr.Row(visible=False):
        batch_in = gr.File(file_count="multiple", file_types=["image"])
        batch_out = gr.JSON()
        batch_btn = gr.Button()
    batch_btn.click(detect_batch, batch_in, batch_out, api_name="detect_batch")
    gr.Markdown(
        "_Tector's detector was trained on real photos and 8 AI generators; it scored 91% on held-out test images. "
        "Results are probabilities, not proof, especially for heavily compressed or edited media._"
    )

if __name__ == "__main__":
    demo.launch()
